#!/bin/bash
SERVER_NAME=ldgs-merchant
APP_HOME=/opt/leedage/app/ldgs-merchant

### BEGIN INIT INFO
#
# Init file for ldgs-merchant daemon
# chkconfig: 2345 66 32
# Provides: $ldgs-merchant
# Required-Start: $network $local_fs $remote_fs
# Required-Stop: $network $local_fs $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: ldgs-merchant daemon
#
### END INIT INFO

# Source function library.
if [ -f /etc/init.d/functions ]; then
  . /etc/init.d/functions
fi

RETVAL=0

export PATH=$PATH:/usr/local/jdk/bin

status() {
        PID=$(ps -ef | grep -v grep | grep -E '\b'''$SERVER_NAME/bin'''\b' | awk '{printf $2}')
        if [ -n "$PID" ];then
            printf "$SERVER_NAME (pid  $PID) is running...\n"
        else
            printf "$SERVER_NAME is stopped.\n" && RETVAL=1
        fi
    }

start() {
        printf "Starting $SERVER_NAME: \t\t\t\t"
        PID=$(ps -ef | grep -v grep | grep -E '\b'''$SERVER_NAME/bin'''\b' | awk '{printf $2}')
        if [ -n "$PID" ];then
            printf "[ running ]\n"
        else
            $APP_HOME/bin/startup.sh start &>/dev/null
            RETVAL=$?
            if [ $RETVAL -eq 0 ];then
                sleep 1
                printf "[ ok ]\n"
            else
                printf "[ failure! ]\n" && RETVAL=$?
            fi
        fi
    }

stop() {
        printf "Stopping $SERVER_NAME: \t\t\t\t"
        PID=$(ps -ef | grep -v grep | grep -E '\b'''$SERVER_NAME/bin'''\b' | awk '{printf $2}')
        if [ ! -n "$PID" ];then
            printf "[ stopped ]\n"
        else
            $APP_HOME/bin/shutdown.sh stop &>/dev/null
            RETVAL=$?
            if [ $RETVAL -eq 0 ];then
                printf "[ ok ]\n"
            else
                printf "[ failure! ]\n" && RETVAL=$?
            fi
        fi
        sleep 3
    }

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        sleep 3
        start
        ;;
    status)
        status
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|status}"
        RETVAL=2
esac
exit $RETVAL

